@userid = 63b475c73892400e88382d72
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJpYXQiOjE2NzMxMjEwMzcsImV4cCI6MTY3MzEyNDYzN30.SYWTgsXMHURZjT1QRXZHixtaIE4wKA1yqUh0AxNpOQ4
@auth = Bearer {{token}}
@deletableUser= 63b9d2a391fc6adf15c34e33
@deletablePass= "111111"
@deletableToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjExNDBfdXNlcl90ZXN0IiwiaWF0IjoxNjczMTIyNDY3LCJleHAiOjE2NzMxMjYwNjd9.Xw7MqogT9iNP9YOIm1nltmj9HZuaCVMs4SlmFL5nSB8
@deletableAuth = Bearer {{token}}

# GET USER WITH POSTS
GET http://localhost:3002/api/v1/users/{{userid}} HTTP/1.1
Content-Type: application/json

###

# DELETE USER
DELETE http://localhost:3002/api/v1/users/{{deletableUser}} HTTP/1.1
Content-Type: application/json
Authorization: {{deletableAuth}}

{
  "password": {{deletablePass}}
}
###

# EDIT USER AVATAR
PATCH http://localhost:3002/api/v1/users/{{userid}} HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}

{
  "avatar": "https://st2.depositphotos.com/3143277/8644/i/600/depositphotos_86446164-stock-photo-business-man-in-office.jpg"
}
###