export const store = {
  displayPosts: [],
  setDisplayPosts: () => {},
  onUpVote: (id) => {},
  onDelPost: () => {},
  fetchPostApi: () => {},
  onCreateNewPost: (postData) => {},
  onEditPost: (id, oldData) => {},
  postIdToEdit: "",
  setPostIdToEdit: () => {},
  onMoreLikeThis: (label) => {},
  isFiltering: false,
  setIsFiltering: () => {},
  labelToDisplay: "",
  setLabelToDisplay: () => {},
  voteRefetch: false,
  setVoteRefetch: () => {},
  specPost: {},
  setSpecPost: () => {},
};

export const specPostTemplate = {
  _id: 0,
  author: { username: "" },
  url: "",
  title: "",
  content: "",
  up_by: [],
  label: "none",
  __v: 0,
  voteCount: 0,
  id: 0,
};
